services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./src:/src
      - ./static:/static
    container_name: fastapi
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ".env"
    container_name: postgres
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/

volumes:
  postgresql_volume: